# Generated by Django 4.2 on 2025-08-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
